image: node:latest

variables:
  AWS_REGION: us-east-1
  JWT_SECRET: $JWT_SECRET
  S3_BUCKET: $S3_BUCKET

stages:
  # - test
  - deploy_staging
  - deploy_production

# test:
#   stage: test
#   script:
#     - npm install
#     - npm test

stage:
  stage: deploy_staging
  before_script:
    - FAILURE_MESSAGE="Must define \$AWS_ACCESS_KEY_ID and \$AWS_SECRET_ACCESS_KEY. Add keys to $CI_PROJECT_URL/-/settings/ci_cd"
    - test -z "$AWS_SECRET_ACCESS_KEY" && echo $FAILURE_MESSAGE && exit 1
    - test -z "$AWS_ACCESS_KEY_ID" && echo $FAILURE_MESSAGE && exit 1
  script:
    - npm install
    - npm run deploy:staging --verbose
  environment: staging
  only:
    - staging
  artifacts:
    paths:
      - stack.json
    expire_in: 2 weeks

production:
  stage: deploy_production
  before_script:
    - FAILURE_MESSAGE="Must define \$AWS_ACCESS_KEY_ID and \$AWS_SECRET_ACCESS_KEY. Add keys to $CI_PROJECT_URL/-/settings/ci_cd"
    - test -z "$AWS_SECRET_ACCESS_KEY" && echo $FAILURE_MESSAGE && exit 1
    - test -z "$AWS_ACCESS_KEY_ID" && echo $FAILURE_MESSAGE && exit 1
  script:
    - npm install
    - npm run deploy:production --verbose
  environment: production
  only:
    - master
  artifacts:
    paths:
      - stack.json
    expire_in: 2 weeks
